<h1 style = "color: blue; text-align: center"> NumPy  </h1>
<h3 style = "color: black; text-align: center"> Produced by: Chih-Hung  Lai <br />
Created: 2017.11.05 Last modified: 2023.04.07

<h2 style = "color: blue"> Table Contents </h2>   

1. Introduction  
 1.1 Features  
 1.2 Why to use Numpy  
 1.3 Get started  
 1.4 Online resource  
2. Basic properties  
3. Creation of ndarray  
 3.1 Create 1 dimentional arrays  
 3.2 Create  n dimentional arrays  
4. Visit  arrays  
5. Slicing arrays  
6. Change the shape of arrays  
7. Array operations  
8. Random Numbers  
9. Generic Functions  
10. Save and read file
 

# 1. Introduction

## 1.1 Features

- Numeric Python
- A fundamental package of multi-dimensional arrays for scientific computing in Python
- A Python library which provides useful functions for multi-dimensional array objects
    - various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- The core of NumPy is ndarray (multi-dimensional array object)
    - an array consists of same data-type elements (like arrays in C language)
    - Python's list allows different data types

## 1.2 Why to use Numpy

- Provide a large number of mathematical functions
    - such as Fourier transform, linear algebra, polynomials, etc.
- accelate operating speed
    - are written in C language
- consume less resource

## 1.3 Get started

In [2]:
import numpy as np
a = [0, 1, 2, 3, 4, 5]
np1 = np.array(a)
print(a)
print(np1)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [50]:
# Function help
# Syntax: numpy.function_name?

import numpy as np
np.sin?

In [1]:
# show numpy version
import numpy
numpy.__version__

'1.20.3'

In [51]:
# using import .. as ..
import numpy as np
arr1 = np.array([10, 15, 20])
print(arr1)
print(type(arr1))

[10 15 20]
<class 'numpy.ndarray'>


## 1.4 Online resource

- official website
    - http://www.numpy.org/

- Documentation
    - https://numpy.org/doc/stable/
    - https://www.w3schools.com/python/numpy/default.asp

# 2. Basic properties

* Data type in Numpy is "ndarray" (n-dimensional array).
* Key features of the ndarray type
    * ndarray.ndim: the dimension of the array
    * ndarray.shape: The shape of the array (represented by a tuple), each integer represents the number of elements in each dimension
    * ndarray.size: the number of elements
    * ndarray.dtype: The data type of the element, including python's built-in int, bool, str, etc. 
        - Note: type () is the data type of the whole object
        - It can also include numpy.int32, numpy.int16, numpy.float64, etc. provided by the NumPy
    * ndarray.itemsize: number of bytes

In [12]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6]])  
print(array, '\n')
print('dimension:', array.ndim)
print('row and column:', array.shape) # number of columns and rows
print('row:', array.shape[0]) # number of row
print('column:', array.shape[1]) # number of column 
print('Number of elements:', array.size)
print('Number of elements in array [0]:', array[0].size)
print('data type(array.dtype):', array.dtype) # display the data type of each element
print('data type(type):', type(array))       # display the data type of the object (or variable) "array"
print('Number of bytes:', array.itemsize)


[[1 2 3]
 [4 5 6]] 

dimension: 2
row and column: (2, 3)
row: 2
column: 3
Number of elements: 6
Number of elements in array [0]: 3
data type(array.dtype): int32
data type(type): <class 'numpy.ndarray'>
Number of bytes: 4


# 3. Creation of ndarray

## 3.1 Create 1 dimentional arrays

1. Use np.array( ) function to convert other data types
    - a = np.array([1, 3, 5, 7, 9]) # From a list   -> more common way
    - b = np.array((1, 3, 5, 7, 9)) # From a tuple
 
2. Use range( ) function or np.arange( ) function
    - Note: parameters in range( ) are only integers, but np.arange( ) can be floats and integers)
    - Not include the "Stop", like Python
3. Use linspace( ) function to create evenly spaced numbers over a specified interval ​​# linearspace
   - linspace(initial value, end value, number of elements, dtype = data type) #will include the end value
   - https://numpy.org/doc/stable/reference/generated/numpy.linspace.html
4. Use other functions, such as zeros( ), ones( ), random.random( ), np.random.randint( )

In [4]:
# Use np.array( ) function to convert other data types

import numpy as np
a = np.array([1, 3, 5, 7, 9])
b = np.array((1, 3, 5, 7, 9))
c = np.array({1, 3, 5, 7, 9})   # every element is an object, not an integer
print(a, b, c, end = '\t')
print()
print(a.dtype, b.dtype, c.dtype) # display the data type of each element
print()
print(type(a), type(b), type(c)) # display the data type of the entire data

a[3] = 100
b[3] = 100
#c[3] = 100 # will cause an error
print(a, b, c, end = '\t')

[1 3 5 7 9] [1 3 5 7 9] {1, 3, 5, 7, 9}	
int32 int32 object

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[  1   3   5 100   9] [  1   3   5 100   9] {1, 3, 5, 7, 9}	

In [15]:
import numpy as np 
arr1 = np.array([5,2,8,4,5,6]) # default data type
arr2 = np.array([5,2,8,4,5,6], dtype = float)
print(arr1, arr2, sep = '\n')
print(arr1.dtype, arr2.dtype)

[5 2 8 4 5 6]
[5. 2. 8. 4. 5. 6.]
int32 float64


In [3]:
# Use np.arange(): can be floats
# np.arange(START, STOP, STEP, dtype=datatype)
# The parameters can be omitted, similar to the usage of python's range() # Will not include the STOP value
import numpy as np
arr1 = np.arange(5) # without 5
arr2 = np.arange(3, 10)
arr3 = np.arange(3, 10, 0.5)
arr4 = np.arange(3, 10, 0.8, dtype = float)
print(arr1, arr2, arr3, arr4, sep = '\n')

[0 1 2 3 4]
[3 4 5 6 7 8 9]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[3.  3.8 4.6 5.4 6.2 7.  7.8 8.6 9.4]


In [21]:
# Use linspace( ) function to create evenly spaced numbers over a specified interval

import numpy as np
arr1 = np.linspace(0, 10, 20) # Contains 10, note that the last argument refers to a total of 20, 
                              # which is divided into 19 intervals, if each interval is 0.5, use 21
print(arr1)

arr2 = np.linspace(0, 10, 21) 
print(arr2)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [12]:
# In addition to the arange(), zeros(), ones() and full() functions, 
# more functions are provided to create arrays of various preset value

import numpy as np
a=np.array([3,6,9,12,15,18])
b=np.arange(6) # 0 .. 6 but not include 6
c = np.zeros(6) # The array has 6 elements with the value 0
d = np.ones(6, dtype = np.int) # The array has 6 elements with the value 1
e = np.random.random(6) # 6 random numbers, 0 .. < 1
f = np.random.randint(1, 100, 10) 
# Generate 10 integers from 1 to 100 (exclusive)
# but random.randint() include 100

print(a,b,c,d,e,f, sep="\n")

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [5]:
import numpy as np
import random

a = [random.randint(1, 6) for i in range(100)]  # include 6, is a list
b = np.random.randint(1, 6, 100)                # not include 6, is a ndarray object
print(a, b, sep="\n\n")
print(type(a), type(b))

[4, 4, 2, 4, 2, 3, 4, 1, 2, 3, 5, 6, 4, 3, 4, 3, 3, 4, 5, 1, 3, 4, 3, 5, 1, 1, 5, 6, 2, 1, 4, 5, 5, 6, 1, 6, 6, 2, 6, 2, 6, 5, 4, 1, 6, 5, 2, 6, 5, 3, 6, 1, 4, 4, 3, 6, 6, 2, 2, 5, 6, 3, 6, 3, 2, 6, 6, 1, 3, 6, 5, 1, 1, 3, 4, 5, 3, 4, 5, 3, 1, 2, 3, 4, 2, 2, 4, 3, 6, 3, 1, 5, 2, 6, 6, 3, 1, 1, 6, 2]

[5 1 4 5 2 2 1 3 2 3 4 1 4 3 1 1 1 5 4 1 2 5 4 1 4 3 1 3 1 1 4 1 1 2 1 2 2
 4 1 2 5 4 1 4 4 4 3 3 1 2 3 4 3 2 4 1 5 3 3 1 5 1 1 4 5 3 3 3 2 2 5 1 2 2
 4 5 4 4 5 4 5 3 3 2 5 3 1 2 3 1 3 4 5 2 2 1 2 5 5 3]
<class 'list'> <class 'numpy.ndarray'>


In [3]:
# NumPy's zeros_like() and ones_like() functions can generate arrays 
# with elements of the same size as 0 or 1 according to the shape of the parameter's template array.

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.zeros_like(a)
print('a:\n', a)
print()
print('np.zeros_like(a):\n', b)

print()
c = np.ones_like(a)
print('np.ones_like(a):\n', c)

print()
d = np.eye(3) # The diagonals are all 1
print('np.eye(3):\n', d)

print()
e = np.eye(3, k=1) # Starting from 1 of the index, the diagonals are all 1, that is, the diagonal diagonal from the position of [0,1] is 1
print('np.eye(3, k=1):\n', e)

print()
f = np.random.rand(3)
print('np.random.rand(3):\n', f)
print()
g = np.random.rand(3,3)
print('np.random.rand(3,3):\n', g)

a:
 [[1 2 3]
 [4 5 6]]

np.zeros_like(a):
 [[0 0 0]
 [0 0 0]]

np.ones_like(a):
 [[1 1 1]
 [1 1 1]]

np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

np.eye(3, k=1):
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

np.random.rand(3):
 [0.61869113 0.36306096 0.64333338]

np.random.rand(3,3):
 [[0.74483067 0.49045504 0.78591469]
 [0.28138438 0.62358562 0.5780462 ]
 [0.09924771 0.11015228 0.44388005]]


In [6]:
# fill the entire array with a certain number

import numpy as np

a = np.full(2, 6) #There are two elements, each is 6
b = np.full((3,3), 5)  # shape is (3, 3)
print("a = np.full(2, 6)", a)
print("b = np.full((3,3), 5)")
print(b)

a = np.full(2, 6) [6 6]
b = np.full((3,3), 5)
[[5 5 5]
 [5 5 5]
 [5 5 5]]


## 3.2 Create  n dimentional arrays

1. Use numpy.array( ) function to convert collections (eg. list or tuple)
   - a=np.array([[3,6,9],[12,15,18]])
2. Use the reshape() function to reshape 1 dimentional arrays
    - b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)

In [43]:
a = np.array([[3,6,9],[12,15,18]])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)
c = np.random.randint(1, 100, 12).reshape(4,3) # 12 integers from 1 to 100 (exclusive)
d = a.reshape(3, 2)
e = np.arange(1, 16).reshape(3, 5)
print(a,b,c,d,e, sep=" \n\n")

[[ 3  6  9]
 [12 15 18]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[12 65 75]
 [48 26 89]
 [39 89 25]
 [86 48 77]] 

[[ 3  6]
 [ 9 12]
 [15 18]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
import numpy as np
a=np.array([[3,6,9],[12,15,18]])
b=np.arange(6).reshape(2,3)
c = np.zeros((2,3))   # The data is all 0
# c = np.zeros(2,3)   is incorrect
d = np.ones((2,3), dtype = int) 
e = np.random.random((2,3)) # 6 random numbers
print(a,b,c,d,e, sep="\n\n")

[[ 3  6  9]
 [12 15 18]]

[[0 1 2]
 [3 4 5]]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1 1 1]
 [1 1 1]]

[[0.58014816 0.87744035 0.3974824 ]
 [0.92403636 0.9506105  0.46016105]]


# 4. Visit  arrays

In [15]:
import numpy as np

a = np.array(np.arange(12).reshape(3,4))
print(a, '\n')
print('a[1, 2]:', a[1, 2], '\n')
# get an element, the element on the 2nd row, 3th column
print('a[2, -1]:', a[2, -1], '\n')
print('a[1]:', a[1], '\n')        
# get a row  (horizontal)
print('a[:, 1]:', a[:, 1], '\n')  
# get a column (vertical)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

a[1, 2]: 6 

a[2, -1]: 11 

a[1]: [4 5 6 7] 

a[:, 1]: [1 5 9] 



In [7]:
import numpy as np

a = np.array(np.arange(12).reshape(3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
for ele in a:
    print(ele)

1
2
3
4
5


In [48]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
for ele in a:
    print(ele)

print()

for ele in a:
    for item in ele:
        print(str(item), end="  ")

[1 2]
[3 4]
[5 6]

1  2  3  4  5  6  

# 5. Slicing arrays

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a)) # str(a) is the string '[1 2 3 4 5 6 7 8 9]'

b = a[1:3] # indices 1,2
print("a[1:3]=" + str(b))
b = a[:4] # indices 0,1,2,3
print("a[:4]=" + str(b))
b = a[3:] # indices 3,4,5,6,7,8
print("a[3:]=" + str(b))
b = a[2:9:3] # indices 2,5,8
print("a[2:9:3]=" + str(b))
b = a[::2] # indices 0,2,4,6,8
print("a[::2]=" + str(b))
b = a[::-1] # indices 8,7,6,5,4,3,2,1,0
print("a[::-1]=" + str(b))
b = a[2:-2] # indices 2,3,4,5,6,7
print("a[2:-2]=" + str(b))

a=[1 2 3 4 5 6 7 8 9]
a[1:3]=[2 3]
a[:4]=[1 2 3 4]
a[3:]=[4 5 6 7 8 9]
a[2:9:3]=[3 6 9]
a[::2]=[1 3 5 7 9]
a[::-1]=[9 8 7 6 5 4 3 2 1]
a[2:-2]=[3 4 5 6 7]


In [1]:
# Given a list of indices, extract the selected elements to create a new array

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("a=" + str(a))

print(a[0], a[2], a[-1]) # indices 0,2, last 1
b = a[[1, 3, 5, 7]] # indices 1,3,5,7
print("a[[1,3,5,7]]=" + str(b))
b = a[range(6)] # indices 0,1,2,3,4,5
print("a[range(6)]=" + str(b))
a[[2, 6]] = 10 # change multiple index values ​​at the same time
print("a[[2,6]]=10->" + str(a))

a=[1 2 3 4 5 6 7 8 9]
1 3 9
a[[1,3,5,7]]=[2 4 6 8]
a[range(6)]=[1 2 3 4 5 6]
a[[2,6]]=10->[ 1  2 10  4  5  6 10  8  9]


In [5]:
# example 2: Given a list of indices, extract the selected elements to create a new array

import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)

print()
b = a[[0,1,2],[0,1,0]] # index [0,0][1,1][2,0]
print("a[[0,1,2],[0,1,0]]=")
print(b)

print()
b = np.array([a[0,0],a[1,1],a[2,0]]) # index [0,0][1,1][2,0]
print("np.array([a[0,0],a[1,1],a[2,0]])=")
print(b)

print()
idx = np.array([0, 2, 0, 1])
print("idx=" + str(idx))
b = a[np.arange(4), idx] # index [0,0][1,2][2,0][3,1]
print("a[np.arange(4),idx]=")
print(b)

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

a[[0,1,2],[0,1,0]]=
[1 5 7]

np.array([a[0,0],a[1,1],a[2,0]])=
[1 5 7]

idx=[0 2 0 1]
a[np.arange(4),idx]=
[ 1  6  7 11]


In [2]:
# Use a boolean array, which is of the same size. 
# If the element value is True, the corresponding element is selected;
# otherwise, it is not selected.

import numpy as np

a = np.array([14,8,10,11,6,3,18,13,12,9])
print("a=" + str(a))
mask = (a % 3 == 0) # create an array of boolean values
print("mask=" + str(mask))
b = a[mask] # use boolean value array to get the value
print("a[mask]=" + str(b))
a[a % 3 == 0] = -1 # change multiple True indexes at the same time
print("a[a%3==0]=-1->" + str(a))

a=[14  8 10 11  6  3 18 13 12  9]
mask=[False False False False  True  True  True False  True  True]
a[mask]=[ 6  3 18 12  9]
a[a%3==0]=-1->[14  8 10 11 -1 -1 -1 13 -1 -1]


In [8]:
# use integer value index

import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
print("a=")
print(a)

print()
mask = (a > 2)
print("mask=")
print(mask)

b = a[mask] # use boolean value array to get the value
print()
print("a[mask]=" + str(b))

a[a > 2] = -1 # Change multiple True indexes at the same time
print()
print("a[a>2]=-1->")
print(a)

a=
[[1 2]
 [3 4]
 [5 6]]

mask=
[[False False]
 [ True  True]
 [ True  True]]

a[mask]=[3 4 5 6]

a[a>2]=-1->
[[ 1  2]
 [-1 -1]
 [-1 -1]]


# 6. Change the shape of arrays

1. Broadcast: perform math operations between different size of arrays
    - When there is a small size of array and a large size of array, NumPy will automatically expand small arrays to perform operations

2. Re-dimension: reshape()

3. Array Flattening: ravel()

4. Transpose: .T (or .transpose())

4. Add dimension: newaxis

In [9]:
# broadcast
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)
print("\nshape of a: " + str(a.shape))

b = np.array([1,0,1])
print()
print("b=\n" + str(b))
print("\nshape of b: " + str(b.shape))

print()
c = a + b
print('a+b:\n', c, sep ='')

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

shape of a: (4, 3)

b=
[1 0 1]

shape of b: (3,)

a+b:
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [12]:
# Array flattening: flatten a two-dimensional array into a one-dimensional array
# python provides two formats: a.raval()  or np.ravel(a)


import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print("a=")
print(a)

b = a.ravel()
print("a.ravel()=" + str(b))
b = np.ravel(a)
print("np.ravel(a)=" + str(b))

a=
[[1 2 3]
 [4 5 6]]
a.ravel()=[1 2 3 4 5 6]
np.ravel(a)=[1 2 3 4 5 6]


In [14]:
# .T
# 3 ways: b.T    b.transpose()    np.transpose(b)

import numpy as np

a = np.array([1,2,3,4,5,6])
print("a=" + str(a))

b = np.reshape(a,(3,2))
print("b=np.reshape(a,(3,2))->")
print(b)

print()
c = b.T
print("c=b.T->")
print(c)

print()
d = b.transpose()
print("d=b.transpose()->")
print(d)

print()
e = np.transpose(b)
print("e=np.transpose(b)->")
print(e)

a=[1 2 3 4 5 6]
b=np.reshape(a,(3,2))->
[[1 2]
 [3 4]
 [5 6]]

c=b.T->
[[1 3 5]
 [2 4 6]]

d=b.transpose()->
[[1 3 5]
 [2 4 6]]

e=np.transpose(b)->
[[1 3 5]
 [2 4 6]]


In [16]:
# newaxis: add dimension

import numpy as np

a = np.array([1,2,3])
print("a=" + str(a))
print('shape:', a.shape)

print()
b = a[:, np.newaxis]
print("b=a[:,np.newaxis]->")
print(b)
print('shape:', b.shape)

print()
c = a[np.newaxis, :]
print("c=a[np.newaxis,:]->")
print(c)
print('shape:', c.shape)

a=[1 2 3]
shape: (3,)

b=a[:,np.newaxis]->
[[1]
 [2]
 [3]]
shape: (3, 1)

c=a[np.newaxis,:]->
[[1 2 3]]
shape: (1, 3)


In [19]:
# array copy and fill value

import numpy as np

a = np.array([1,2,3])
print("a=" + str(a))

b = a.copy() # If b = a is not used, a and b will point to the same address. 
# When the content is modified, the content of both will be changed together
# see the next code

print("b=a.copy()->" + str(b))
b.fill(4)
print("b.fill(4)=" + str(b))

a=[1 2 3]
b=a.copy()->[1 2 3]
b.fill(4)=[4 4 4]
c=np.concatenate((a,b))->[1 2 3 4 4 4]
a+b->[5 6 7]


In [12]:
import numpy as np
a = [1, 2, 3]
b = a
b[0] = 2
print("a:", a)
print("b:", b)


c = np.array([1, 2, 3])
d = c
d[0] = 2
print("c:", c)
print("d:", d)

a: [2, 2, 3]
b: [2, 2, 3]
c: [2 2 3]
d: [2 2 3]


## 7. Array operations

### universal function (referred to as ufunc) 

- Meaning: Numpy provides a function that operates on all elements
    - For example: np.sum(), np.square(), np.sin()...

- Note: Use the following method to see whether it is belong to ufunc in type  
    - numpy.function_name?

In [13]:
import numpy as np

np.sin?

Call signature:  np.sin(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'sin'>
File:            c:\users\laich\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Trigonometric sine, element-wise.

Parameters
----------
x : array_like
    Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its o

In [21]:
# operations on Array and constant 

import numpy as np
a=np.array([[3,6,9],[12,15,18]])
b = a + 3
print(b)

[[ 6  9 12]
 [15 18 21]]


In [22]:
# Addition, subtraction, multiplication and division of two arrays (*non-matrix multiplication*)
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
b=np.arange(1,7).reshape((2,3))
print("a:\n", a)
print("\nb:\n", b)
print("\na+b:\n", a+b)
print("\na-b:\n", a-b)
print("\na*b:\n", a*b)
print("\na/b:\n", a/b)

a:
 [[ 2  4  6]
 [ 8 10 12]]

b:
 [[1 2 3]
 [4 5 6]]

a+b:
 [[ 3  6  9]
 [12 15 18]]

a-b:
 [[1 2 3]
 [4 5 6]]

a*b:
 [[ 2  8 18]
 [32 50 72]]

a/b:
 [[2. 2. 2.]
 [2. 2. 2.]]


In [23]:
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
a = a ** 2 # square
print(a)

print()
print(a>10)

[[  4  16  36]
 [ 64 100 144]]

[[False  True  True]
 [ True  True  True]]


In [17]:
# matrix multiplication numpy.dot()
import numpy as np
a=np.array([[2,4,6],[8,10,12]])
b=np.arange(6).reshape((2,3))
print("a=")
print(a)
print("b=")
print(b)
print("b.T=")
print(b.T) # transpose
print("np.dot(a, b.T)")
print(np.dot(a,b.T))

a=
[[ 2  4  6]
 [ 8 10 12]]
b=
[[0 1 2]
 [3 4 5]]
b.T=
[[0 3]
 [1 4]
 [2 5]]
np.dot(a, b.T)
[[ 16  52]
 [ 34 124]]


In [26]:
# We can specify the connection direction of the parameter axis axis
# the parameter value 0 is the vertical direction, which can be connected below the two-dimensional array; 
# the value 1 is the horizontal direction

import numpy as np
a=np.array([[3,6,9],[12,15,18]])

print(a)
print()
print("sum(a):", np.sum(a))
print("sum(a, axis=1):",np.sum(a, axis=1))

print("sum(a, axis=0):",np.sum(a, axis=0))

print(a.sum(axis = 1))

[[ 3  6  9]
 [12 15 18]]

sum(a): 63
sum(a, axis=1): [18 45]
sum(a, axis=0): [15 21 27]
[18 45]


#### concatenate( ) can merge two arrays or join elements

In [29]:
# When using the np.concatenate() function to concatenate two-dimensional arrays,
# axis: 0 is the vertical direction (the default is 0)
# axis: 1 is the horizontal direction

import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.concatenate((a,b))            # default of axis is 0
print("c=np.concatenate((a,b))->")
print(c)
c = np.concatenate((a,b), axis=0)
print("c=np.concatenate((a,b), axis=0)->")
print(c)
c = np.concatenate((a,b), axis=1)
print("c=np.concatenate((a,b), axis=1)->")
print(c)

c=np.concatenate((a,b))->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=0)->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=1)->
[[1 2 5 6]
 [3 4 7 8]]


In [28]:
import numpy as np
a = np.array([2,4,6,8,10,12])
b = np.arange(10)
c = np.concatenate((a,b))
d = np.concatenate((a,[10,20]))
print(a,b,c,d, sep="\n\n")

[ 2  4  6  8 10 12]

[0 1 2 3 4 5 6 7 8 9]

[ 2  4  6  8 10 12  0  1  2  3  4  5  6  7  8  9]

[ 2  4  6  8 10 12 10 20]


In [18]:
# Numpy Array Merger

import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
print("np.vstack((A,B))")
print(np.vstack((A,B))) #vertical
print("np.hstack((A,B))")
print(np.hstack((A,B))) #horizontal, same as np.concatenate((A, B), axis=0)
print("np.concatenate((A, B), axis=0)")
c = np.concatenate((A, B), axis=0)
print(c)

np.vstack((A,B))
[[1 1 1]
 [2 2 2]]
np.hstack((A,B))
[1 1 1 2 2 2]
np.concatenate((A, B), axis=0)
[1 1 1 2 2 2]


# 8. Random Numbers

### The format is: numpy.random.Random_Method()

-numpy.random.randint(1, 6, 5)

- random ( ): Generates random numbers between 0.0 and 1.0, such as 0.7298076072029743
- random (5): Generates 5 random numbers between 0.0 and 1.0, which form a series of 5 elements, such as [0.58607119 0.37147243 0.05337405 0.49300567 0.10304672]
-random ((3,4))): Generate random numbers in a two-dimensional array

### - numpy.random.randint (min, max, size)
    - np.random.randint(low=0, high=2, size=10)
    - Generate a random integer between min ~ max (exclude max)
    - randint(5, 10): Generate an integer random number between 5 and 10, 10 excluded
    - randint(5, 10, 6): Generates an array of 6 integers from 5 to 10 (exclusive)
    - randint(1, 101, (3,4)): Generate a two-dimensional array of 3 * 4 integers from 1 to 101 (exclusive)

In [16]:
import numpy as np
import random

throws1 = np.random.randint(0, 2)  # exclude 2
throws2 = random.randint(0,2)  # include 2

throws3 = np.random.randint(low=0, high=2, size=10) # 100 random numbers
throws4 = np.random.randint(0, 2, 10)  # 10 random numbers, no argument names
throws5 = np.random.randint(0, 2, (3,4))
print("throws1:", throws1)
print("throws2:", throws2)
print("throws3:", throws3)
print("throws4:", throws4)
print("throws5:\n", throws5)

throws1: 0
throws2: 2
throws3: [1 1 1 0 1 0 0 0 0 0]
throws4: [0 0 1 1 0 1 1 0 0 1]
throws5:
 [[0 1 0 1]
 [1 1 0 1]
 [1 0 0 0]]


In [10]:
# The difference between random.randint() and numpy.random.randint()
# random.randint() can generate only one integr once and include the max integer 

import numpy as np
import random

a = [i for i in np.random.randint(0, 2, 20)]
b = [random.randint(0, 2) for i in range(20)]
print(a)
print(b)

[1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[0, 2, 1, 2, 0, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0]


###  numpy.random.rand( ): 
- Generate random values (or multidimensional arrays)
- rand(): Generate a random number between 0 and 1
    - 0.9760298522559884
- rand(5): Generate an array of 5 random numbers
    - [0.64355233 0.06190279 0.0139926 0.49136906 0.18873564]
- rand(3,2,4): Generate three-dimensional random numbers

In [11]:
import numpy as np
print(np.random.rand())
print()

print (np.random.rand(5)) # A list of 5 random values
print ()
print (np.random.rand(3,2,4)) # Three-dimensional random numbers

0.14830968930303678

[0.515932   0.04348586 0.63280939 0.44460455 0.95666505]

[[[0.81812979 0.62287394 0.22784685 0.69673895]
  [0.3505662  0.75817138 0.27654977 0.31212694]]

 [[0.39957131 0.20764292 0.06376403 0.29482427]
  [0.19981355 0.72379316 0.44837302 0.18464895]]

 [[0.24539718 0.55596855 0.97351022 0.89004727]
  [0.62415475 0.79252854 0.30423708 0.00430826]]]


### More reference
- Random Numbers in NumPy
    - https://www.w3schools.com/python/numpy/numpy_random.asp
- Random Data Distribution
    - https://www.w3schools.com/python/numpy/numpy_random_distribution.asp

# 9. Generic Functions

### NumPy provides many common functions for arrays

* add(x1, x2) 
* subtract(x1, x2) 
* multiply(x1, x2) 
* divide(x1, x2) 
* mod(x1, x2) 
* power(x1, x2)
* isfinite(x) 
* isinf(x) 
* isnan(x) 
* sign(x)
* negative(x) 
* absolute(x) 
* sum(x) 
* max(x) 
* min(x) 

* rint(x) 
* floor(x) 
* ceil(x) 
* sqrt(x) 
* square(x) 
* exp(x) 
* exp2(x) 
* log(x) 
* log2(x) 
* log10(x) 
* cos (x), sin (x), tan (x), acos (x), asin (x), atan (x)
* average(x)
    * Average with missing values: np.mean(data frame object or field)
    * Average without missing values: np.nanmean(data frame object or field)
* median (x)median
    * Median with missing values: np.median(data frame object or field)
    * Median without missing values: np.nanmedian(data frame object or field)
* std(x)
    * Divided into two types: maternal number estimation and sample standard deviation, see the lecture notes in the statistics course


In [15]:
# Trigonometric functions

import numpy as np

a = np.array([30,45,60]) 

print(np.sin(a*np.pi/180)) 
print(np.cos(a*np.pi/180)) 
print(np.tan(a*np.pi/180)) 

[0.5        0.70710678 0.8660254 ]
[0.8660254  0.70710678 0.5       ]
[0.57735027 1.         1.73205081]


In [19]:
# Find average

import numpy as np
a = [[1,2,3], [4,5,6]]
print(a)
print("np.mean(a)")
print(np.mean(a))
print("np.mean(a, axis = 0)")
print(np.mean(a, axis = 0))
print("np.mean(a, 0)")
print(np.mean(a, 0))
print("np.mean(a, axis = 1)")
print(np.mean(a, axis = 1))
print("np.mean(a, 1)")
print(np.mean(a, 1))

[[1, 2, 3], [4, 5, 6]]
np.mean(a)
3.5
np.mean(a, axis = 0)
[2.5 3.5 4.5]
np.mean(a, 0)
[2.5 3.5 4.5]
np.mean(a, axis = 1)
[2. 5.]
np.mean(a, 1)
[2. 5.]


In [17]:
import numpy as np

b = np.array([np.nan, 10, 20])
print(b)
print(np.mean(b))
print(np.nanmean(b))

[nan 10. 20.]
nan
15.0


# 10. Save and read file

In [ ]:
# save the array as a file

In [20]:
# binary file

import numpy as np

a = np.arange(10)
outputfile = "Example.npy"
with open(outputfile, 'wb') as fp:
    np.save(fp, a)

In [21]:
# Set the separator character, delimiter = ','
# savetxt save in CSV format

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
outputfile = "Example1.csv"
np.savetxt(outputfile, a, delimiter=',')

In [105]:
# Example.csv
1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00

(4.0, 5.0, 6.0)

In [22]:
# Set the separator character, delimiter = ','
# savetxt save in CSV format
import numpy as np

a = np.array([[1,2,3],[4,5,6]], dtype = int)
outputfile = "Example.out"
np.savetxt(outputfile, a, delimiter=',')
print(a)

[[1 2 3]
 [4 5 6]]


In [107]:
# Example.out
1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00

(4.0, 5.0, 6.0)

In [ ]:
# Read binary file

import numpy as np

outputfile = "Example.npy"
with open(outputfile, 'rb') as fp:
    a = np.load(fp)
print(a)

In [23]:
# Read text file

import numpy as np

outputfile = "Example.out"
a = np.loadtxt(outputfile, delimiter=',')
print(a)
print()

b = a.astype(int)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]

[[1 2 3]
 [4 5 6]]


## Reference:
- Yunjie Chen  (2018). Python data science and artificial intelligence application practice. Taipei: Flag.
- W3School website
- Numpy official website

### Advanced topic: Structured array
- https://numpy.org/doc/stable/user/basics.rec.html
- https://iter01.com/597990.html